; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/bost/dev/hochzeit/src/hochzeit/crossover.clj

(ns hochzeit.crossover)

(defn f [] (* 1 11))
(defn s [] "foo")
