; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/bost/dev/hochzeit/src/hochzeit/crossover.clj

(ns hochzeit.crossover
  ;; (:require [hochzeit.core :as c])
)

(defn f [] (* 1 11))
(defn s [] "foo")

(defn e []
   [{:time 1297110662 :value 88},
    {:time 1297110663 :value 33},
    {:time 1297110663 :value 51},
    {:time 1297110664 :value 53},
    {:time 1297110665 :value 58},
    {:time 1297110666 :value 59},]

   ;; (into [] (c/e [[:EUR :BTC] [:PPC :USD]]
   ;;               ["/home/bost/vircurex-flat/vircurex.2013-05-17_03-05-04.xml"
   ;;                "/home/bost/vircurex-flat/vircurex.2013-04-14_11-50-26.xml"]))
)
   
