; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/bost/dev/hochzeit/src/hochzeit/macros.clj

(ns hochzeit.macros
  (:require [clojure.pprint :as pprint])
  (:import java.io.File))

(defmacro load-template [relative-uri]
  "Reads and returns a template as a string."
  (slurp relative-uri))
